development:
  secret_key_base: <%= ENV['PERSONAL_WEBSITE_SECRET_TOKEN'] %>

test:
  secret_key_base: <%= ENV['PERSONAL_WEBSITE_SECRET_TOKEN'] %>

production:
  secret_key_base: <%= ENV['PERSONAL_WEBSITE_SECRET_TOKEN'] %>
